/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq;


import dev.laarryy.atropos.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Atropos extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atropos</code>
     */
    public static final Atropos ATROPOS = new Atropos();

    /**
     * The table <code>atropos.permissions</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>atropos.punishments</code>.
     */
    public final Punishments PUNISHMENTS = Punishments.PUNISHMENTS;

    /**
     * The table <code>atropos.server_blacklist</code>.
     */
    public final ServerBlacklist SERVER_BLACKLIST = ServerBlacklist.SERVER_BLACKLIST;

    /**
     * The table <code>atropos.server_command_uses</code>.
     */
    public final ServerCommandUses SERVER_COMMAND_USES = ServerCommandUses.SERVER_COMMAND_USES;

    /**
     * The table <code>atropos.server_messages</code>.
     */
    public final ServerMessages SERVER_MESSAGES = ServerMessages.SERVER_MESSAGES;

    /**
     * The table <code>atropos.server_properties</code>.
     */
    public final ServerProperties SERVER_PROPERTIES = ServerProperties.SERVER_PROPERTIES;

    /**
     * The table <code>atropos.server_role_permissions</code>.
     */
    public final ServerRolePermissions SERVER_ROLE_PERMISSIONS = ServerRolePermissions.SERVER_ROLE_PERMISSIONS;

    /**
     * The table <code>atropos.server_user</code>.
     */
    public final ServerUser SERVER_USER = ServerUser.SERVER_USER;

    /**
     * The table <code>atropos.servers</code>.
     */
    public final Servers SERVERS = Servers.SERVERS;

    /**
     * The table <code>atropos.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Atropos() {
        super("atropos", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Permissions.PERMISSIONS,
            Punishments.PUNISHMENTS,
            ServerBlacklist.SERVER_BLACKLIST,
            ServerCommandUses.SERVER_COMMAND_USES,
            ServerMessages.SERVER_MESSAGES,
            ServerProperties.SERVER_PROPERTIES,
            ServerRolePermissions.SERVER_ROLE_PERMISSIONS,
            ServerUser.SERVER_USER,
            Servers.SERVERS,
            Users.USERS
        );
    }
}
