/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq;


import dev.laarryy.atropos.jooq.tables.Permissions;
import dev.laarryy.atropos.jooq.tables.Punishments;
import dev.laarryy.atropos.jooq.tables.ServerBlacklist;
import dev.laarryy.atropos.jooq.tables.ServerCommandUses;
import dev.laarryy.atropos.jooq.tables.ServerMessages;
import dev.laarryy.atropos.jooq.tables.ServerProperties;
import dev.laarryy.atropos.jooq.tables.ServerRolePermissions;
import dev.laarryy.atropos.jooq.tables.ServerUser;
import dev.laarryy.atropos.jooq.tables.Servers;
import dev.laarryy.atropos.jooq.tables.Users;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    public static final Punishments PUNISHMENTS = Punishments.PUNISHMENTS;

    public static final ServerBlacklist SERVER_BLACKLIST = ServerBlacklist.SERVER_BLACKLIST;

    public static final ServerCommandUses SERVER_COMMAND_USES = ServerCommandUses.SERVER_COMMAND_USES;

    public static final ServerMessages SERVER_MESSAGES = ServerMessages.SERVER_MESSAGES;

    public static final ServerProperties SERVER_PROPERTIES = ServerProperties.SERVER_PROPERTIES;

    public static final ServerRolePermissions SERVER_ROLE_PERMISSIONS = ServerRolePermissions.SERVER_ROLE_PERMISSIONS;

    public static final ServerUser SERVER_USER = ServerUser.SERVER_USER;

    public static final Servers SERVERS = Servers.SERVERS;

    public static final Users USERS = Users.USERS;
}
