/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables;


import dev.laarryy.atropos.jooq.Atropos;
import dev.laarryy.atropos.jooq.Keys;
import dev.laarryy.atropos.jooq.tables.records.ServerUserRecord;
import dev.laarryy.atropos.jooq.tables.Servers.ServersPath;
import dev.laarryy.atropos.jooq.tables.Users.UsersPath;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerUser extends TableImpl<ServerUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atropos.server_user</code>
     */
    public static final ServerUser SERVER_USER = new ServerUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServerUserRecord> getRecordType() {
        return ServerUserRecord.class;
    }

    /**
     * The column <code>atropos.server_user.id</code>.
     */
    public final TableField<ServerUserRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>atropos.server_user.user_id</code>.
     */
    public final TableField<ServerUserRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>atropos.server_user.server_id</code>.
     */
    public final TableField<ServerUserRecord, Integer> SERVER_ID = createField(DSL.name("server_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>atropos.server_user.date</code>.
     */
    public final TableField<ServerUserRecord, Long> DATE = createField(DSL.name("date"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private ServerUser(Name alias, Table<ServerUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ServerUser(Name alias, Table<ServerUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atropos.server_user</code> table reference
     */
    public ServerUser(String alias) {
        this(DSL.name(alias), SERVER_USER);
    }

    /**
     * Create an aliased <code>atropos.server_user</code> table reference
     */
    public ServerUser(Name alias) {
        this(alias, SERVER_USER);
    }

    /**
     * Create a <code>atropos.server_user</code> table reference
     */
    public ServerUser() {
        this(DSL.name("server_user"), null);
    }

    public <O extends Record> ServerUser(Table<O> path, ForeignKey<O, ServerUserRecord> childPath, InverseForeignKey<O, ServerUserRecord> parentPath) {
        super(path, childPath, parentPath, SERVER_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServerUserPath extends ServerUser implements Path<ServerUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServerUserPath(Table<O> path, ForeignKey<O, ServerUserRecord> childPath, InverseForeignKey<O, ServerUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServerUserPath(Name alias, Table<ServerUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServerUserPath as(String alias) {
            return new ServerUserPath(DSL.name(alias), this);
        }

        @Override
        public ServerUserPath as(Name alias) {
            return new ServerUserPath(alias, this);
        }

        @Override
        public ServerUserPath as(Table<?> alias) {
            return new ServerUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Atropos.ATROPOS;
    }

    @Override
    public Identity<ServerUserRecord, Integer> getIdentity() {
        return (Identity<ServerUserRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServerUserRecord> getPrimaryKey() {
        return Keys.KEY_SERVER_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<ServerUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SERVER_USER_ID);
    }

    @Override
    public List<ForeignKey<ServerUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SERVER_USER_IBFK_1, Keys.SERVER_USER_IBFK_2);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>atropos.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SERVER_USER_IBFK_1, null);

        return _users;
    }

    private transient ServersPath _servers;

    /**
     * Get the implicit join path to the <code>atropos.servers</code> table.
     */
    public ServersPath servers() {
        if (_servers == null)
            _servers = new ServersPath(this, Keys.SERVER_USER_IBFK_2, null);

        return _servers;
    }

    @Override
    public ServerUser as(String alias) {
        return new ServerUser(DSL.name(alias), this);
    }

    @Override
    public ServerUser as(Name alias) {
        return new ServerUser(alias, this);
    }

    @Override
    public ServerUser as(Table<?> alias) {
        return new ServerUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerUser rename(String name) {
        return new ServerUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerUser rename(Name name) {
        return new ServerUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ServerUser rename(Table<?> name) {
        return new ServerUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser where(Condition condition) {
        return new ServerUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ServerUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ServerUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
