/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.Permissions;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsRecord extends UpdatableRecordImpl<PermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.permissions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.permissions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.permissions.permission</code>.
     */
    public void setPermission(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.permissions.permission</code>.
     */
    public String getPermission() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionsRecord
     */
    public PermissionsRecord() {
        super(Permissions.PERMISSIONS);
    }

    /**
     * Create a detached, initialised PermissionsRecord
     */
    public PermissionsRecord(Integer id, String permission) {
        super(Permissions.PERMISSIONS);

        setId(id);
        setPermission(permission);
        resetChangedOnNotNull();
    }
}
