/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.Punishments;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PunishmentsRecord extends UpdatableRecordImpl<PunishmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.punishments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.punishments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.punishments.user_id_punished</code>.
     */
    public void setUserIdPunished(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.punishments.user_id_punished</code>.
     */
    public Integer getUserIdPunished() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atropos.punishments.name_punished</code>.
     */
    public void setNamePunished(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>atropos.punishments.name_punished</code>.
     */
    public String getNamePunished() {
        return (String) get(2);
    }

    /**
     * Setter for <code>atropos.punishments.user_id_punisher</code>.
     */
    public void setUserIdPunisher(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>atropos.punishments.user_id_punisher</code>.
     */
    public Integer getUserIdPunisher() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>atropos.punishments.name_punisher</code>.
     */
    public void setNamePunisher(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>atropos.punishments.name_punisher</code>.
     */
    public String getNamePunisher() {
        return (String) get(4);
    }

    /**
     * Setter for <code>atropos.punishments.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>atropos.punishments.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_type</code>.
     */
    public void setPunishmentType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_type</code>.
     */
    public String getPunishmentType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_date</code>.
     */
    public void setPunishmentDate(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_date</code>.
     */
    public Instant getPunishmentDate() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_message</code>.
     */
    public void setPunishmentMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_message</code>.
     */
    public String getPunishmentMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>atropos.punishments.permanent</code>.
     */
    public void setPermanent(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>atropos.punishments.permanent</code>.
     */
    public Boolean getPermanent() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>atropos.punishments.automatic</code>.
     */
    public void setAutomatic(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>atropos.punishments.automatic</code>.
     */
    public Boolean getAutomatic() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_end_date</code>.
     */
    public void setPunishmentEndDate(Instant value) {
        set(11, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_end_date</code>.
     */
    public Instant getPunishmentEndDate() {
        return (Instant) get(11);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_end_reason</code>.
     */
    public void setPunishmentEndReason(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_end_reason</code>.
     */
    public String getPunishmentEndReason() {
        return (String) get(12);
    }

    /**
     * Setter for <code>atropos.punishments.did_dm</code>.
     */
    public void setDidDm(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>atropos.punishments.did_dm</code>.
     */
    public Boolean getDidDm() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>atropos.punishments.end_date_passed</code>.
     */
    public void setEndDatePassed(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>atropos.punishments.end_date_passed</code>.
     */
    public Boolean getEndDatePassed() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>atropos.punishments.punishment_ender</code>.
     */
    public void setPunishmentEnder(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>atropos.punishments.punishment_ender</code>.
     */
    public Integer getPunishmentEnder() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>atropos.punishments.name_punishment_ender</code>.
     */
    public void setNamePunishmentEnder(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>atropos.punishments.name_punishment_ender</code>.
     */
    public String getNamePunishmentEnder() {
        return (String) get(16);
    }

    /**
     * Setter for <code>atropos.punishments.automatic_end</code>.
     */
    public void setAutomaticEnd(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>atropos.punishments.automatic_end</code>.
     */
    public Boolean getAutomaticEnd() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>atropos.punishments.batch_id</code>.
     */
    public void setBatchId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>atropos.punishments.batch_id</code>.
     */
    public Integer getBatchId() {
        return (Integer) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PunishmentsRecord
     */
    public PunishmentsRecord() {
        super(Punishments.PUNISHMENTS);
    }

    /**
     * Create a detached, initialised PunishmentsRecord
     */
    public PunishmentsRecord(Integer id, Integer userIdPunished, String namePunished, Integer userIdPunisher, String namePunisher, Integer serverId, String punishmentType, Instant punishmentDate, String punishmentMessage, Boolean permanent, Boolean automatic, Instant punishmentEndDate, String punishmentEndReason, Boolean didDm, Boolean endDatePassed, Integer punishmentEnder, String namePunishmentEnder, Boolean automaticEnd, Integer batchId) {
        super(Punishments.PUNISHMENTS);

        setId(id);
        setUserIdPunished(userIdPunished);
        setNamePunished(namePunished);
        setUserIdPunisher(userIdPunisher);
        setNamePunisher(namePunisher);
        setServerId(serverId);
        setPunishmentType(punishmentType);
        setPunishmentDate(punishmentDate);
        setPunishmentMessage(punishmentMessage);
        setPermanent(permanent);
        setAutomatic(automatic);
        setPunishmentEndDate(punishmentEndDate);
        setPunishmentEndReason(punishmentEndReason);
        setDidDm(didDm);
        setEndDatePassed(endDatePassed);
        setPunishmentEnder(punishmentEnder);
        setNamePunishmentEnder(namePunishmentEnder);
        setAutomaticEnd(automaticEnd);
        setBatchId(batchId);
        resetChangedOnNotNull();
    }
}
