/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.Punishments;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.Instant;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PunishmentsRecord extends UpdatableRecordImpl<PunishmentsRecord> implements Record22<Integer, Integer, String, String, Integer, String, String, Integer, String, Instant, String, Boolean, Boolean, Instant, String, Boolean, Boolean, Integer, String, String, Boolean, Integer> {

    private static final long serialVersionUID = 1L;

    public PunishmentsRecord setId(@NonNull Integer value) {
        set(0, value);
        return this;
    }

    @NonNull
    public Integer getId() {
        return (Integer) get(0);
    }

    public PunishmentsRecord setUserIdPunished(@NonNull Integer value) {
        set(1, value);
        return this;
    }

    @NonNull
    public Integer getUserIdPunished() {
        return (Integer) get(1);
    }

    public PunishmentsRecord setNamePunished(@Nullable String value) {
        set(2, value);
        return this;
    }

    @Nullable
    public String getNamePunished() {
        return (String) get(2);
    }

    public PunishmentsRecord setDiscrimPunished(@Nullable String value) {
        set(3, value);
        return this;
    }

    @Nullable
    public String getDiscrimPunished() {
        return (String) get(3);
    }

    public PunishmentsRecord setUserIdPunisher(@NonNull Integer value) {
        set(4, value);
        return this;
    }

    @NonNull
    public Integer getUserIdPunisher() {
        return (Integer) get(4);
    }

    public PunishmentsRecord setNamePunisher(@Nullable String value) {
        set(5, value);
        return this;
    }

    @Nullable
    public String getNamePunisher() {
        return (String) get(5);
    }

    public PunishmentsRecord setDiscrimPunisher(@Nullable String value) {
        set(6, value);
        return this;
    }

    @Nullable
    public String getDiscrimPunisher() {
        return (String) get(6);
    }

    public PunishmentsRecord setServerId(@NonNull Integer value) {
        set(7, value);
        return this;
    }

    @NonNull
    public Integer getServerId() {
        return (Integer) get(7);
    }

    public PunishmentsRecord setPunishmentType(@NonNull String value) {
        set(8, value);
        return this;
    }

    @NonNull
    public String getPunishmentType() {
        return (String) get(8);
    }

    public PunishmentsRecord setPunishmentDate(@NonNull Instant value) {
        set(9, value);
        return this;
    }

    @NonNull
    public Instant getPunishmentDate() {
        return (Instant) get(9);
    }

    public PunishmentsRecord setPunishmentMessage(@Nullable String value) {
        set(10, value);
        return this;
    }

    @Nullable
    public String getPunishmentMessage() {
        return (String) get(10);
    }

    public PunishmentsRecord setPermanent(@NonNull Boolean value) {
        set(11, value);
        return this;
    }

    @NonNull
    public Boolean getPermanent() {
        return (Boolean) get(11);
    }

    public PunishmentsRecord setAutomatic(@NonNull Boolean value) {
        set(12, value);
        return this;
    }

    @NonNull
    public Boolean getAutomatic() {
        return (Boolean) get(12);
    }

    public PunishmentsRecord setPunishmentEndDate(@Nullable Instant value) {
        set(13, value);
        return this;
    }

    @Nullable
    public Instant getPunishmentEndDate() {
        return (Instant) get(13);
    }

    public PunishmentsRecord setPunishmentEndReason(@Nullable String value) {
        set(14, value);
        return this;
    }

    @Nullable
    public String getPunishmentEndReason() {
        return (String) get(14);
    }

    public PunishmentsRecord setDidDm(@NonNull Boolean value) {
        set(15, value);
        return this;
    }

    @NonNull
    public Boolean getDidDm() {
        return (Boolean) get(15);
    }

    public PunishmentsRecord setEndDatePassed(@NonNull Boolean value) {
        set(16, value);
        return this;
    }

    @NonNull
    public Boolean getEndDatePassed() {
        return (Boolean) get(16);
    }

    public PunishmentsRecord setPunishmentEnder(@Nullable Integer value) {
        set(17, value);
        return this;
    }

    @Nullable
    public Integer getPunishmentEnder() {
        return (Integer) get(17);
    }

    public PunishmentsRecord setNamePunishmentEnder(@Nullable String value) {
        set(18, value);
        return this;
    }

    @Nullable
    public String getNamePunishmentEnder() {
        return (String) get(18);
    }

    public PunishmentsRecord setDiscrimPunishmentEnder(@Nullable String value) {
        set(19, value);
        return this;
    }

    @Nullable
    public String getDiscrimPunishmentEnder() {
        return (String) get(19);
    }

    public PunishmentsRecord setAutomaticEnd(@NonNull Boolean value) {
        set(20, value);
        return this;
    }

    @NonNull
    public Boolean getAutomaticEnd() {
        return (Boolean) get(20);
    }

    public PunishmentsRecord setBatchId(@Nullable Integer value) {
        set(21, value);
        return this;
    }

    @Nullable
    public Integer getBatchId() {
        return (Integer) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Row22<Integer, Integer, String, String, Integer, String, String, Integer, String, Instant, String, Boolean, Boolean, Instant, String, Boolean, Boolean, Integer, String, String, Boolean, Integer> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    @NonNull
    public Row22<Integer, Integer, String, String, Integer, String, String, Integer, String, Instant, String, Boolean, Boolean, Instant, String, Boolean, Boolean, Integer, String, String, Boolean, Integer> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    @NonNull
    public Field<Integer> field1() {
        return Punishments.PUNISHMENTS.ID;
    }

    @Override
    @NonNull
    public Field<Integer> field2() {
        return Punishments.PUNISHMENTS.USER_ID_PUNISHED;
    }

    @Override
    @NonNull
    public Field<String> field3() {
        return Punishments.PUNISHMENTS.NAME_PUNISHED;
    }

    @Override
    @NonNull
    public Field<String> field4() {
        return Punishments.PUNISHMENTS.DISCRIM_PUNISHED;
    }

    @Override
    @NonNull
    public Field<Integer> field5() {
        return Punishments.PUNISHMENTS.USER_ID_PUNISHER;
    }

    @Override
    @NonNull
    public Field<String> field6() {
        return Punishments.PUNISHMENTS.NAME_PUNISHER;
    }

    @Override
    @NonNull
    public Field<String> field7() {
        return Punishments.PUNISHMENTS.DISCRIM_PUNISHER;
    }

    @Override
    @NonNull
    public Field<Integer> field8() {
        return Punishments.PUNISHMENTS.SERVER_ID;
    }

    @Override
    @NonNull
    public Field<String> field9() {
        return Punishments.PUNISHMENTS.PUNISHMENT_TYPE;
    }

    @Override
    @NonNull
    public Field<Instant> field10() {
        return Punishments.PUNISHMENTS.PUNISHMENT_DATE;
    }

    @Override
    @NonNull
    public Field<String> field11() {
        return Punishments.PUNISHMENTS.PUNISHMENT_MESSAGE;
    }

    @Override
    @NonNull
    public Field<Boolean> field12() {
        return Punishments.PUNISHMENTS.PERMANENT;
    }

    @Override
    @NonNull
    public Field<Boolean> field13() {
        return Punishments.PUNISHMENTS.AUTOMATIC;
    }

    @Override
    @NonNull
    public Field<Instant> field14() {
        return Punishments.PUNISHMENTS.PUNISHMENT_END_DATE;
    }

    @Override
    @NonNull
    public Field<String> field15() {
        return Punishments.PUNISHMENTS.PUNISHMENT_END_REASON;
    }

    @Override
    @NonNull
    public Field<Boolean> field16() {
        return Punishments.PUNISHMENTS.DID_DM;
    }

    @Override
    @NonNull
    public Field<Boolean> field17() {
        return Punishments.PUNISHMENTS.END_DATE_PASSED;
    }

    @Override
    @NonNull
    public Field<Integer> field18() {
        return Punishments.PUNISHMENTS.PUNISHMENT_ENDER;
    }

    @Override
    @NonNull
    public Field<String> field19() {
        return Punishments.PUNISHMENTS.NAME_PUNISHMENT_ENDER;
    }

    @Override
    @NonNull
    public Field<String> field20() {
        return Punishments.PUNISHMENTS.DISCRIM_PUNISHMENT_ENDER;
    }

    @Override
    @NonNull
    public Field<Boolean> field21() {
        return Punishments.PUNISHMENTS.AUTOMATIC_END;
    }

    @Override
    @NonNull
    public Field<Integer> field22() {
        return Punishments.PUNISHMENTS.BATCH_ID;
    }

    @Override
    @NonNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer component2() {
        return getUserIdPunished();
    }

    @Override
    @Nullable
    public String component3() {
        return getNamePunished();
    }

    @Override
    @Nullable
    public String component4() {
        return getDiscrimPunished();
    }

    @Override
    @NonNull
    public Integer component5() {
        return getUserIdPunisher();
    }

    @Override
    @Nullable
    public String component6() {
        return getNamePunisher();
    }

    @Override
    @Nullable
    public String component7() {
        return getDiscrimPunisher();
    }

    @Override
    @NonNull
    public Integer component8() {
        return getServerId();
    }

    @Override
    @NonNull
    public String component9() {
        return getPunishmentType();
    }

    @Override
    @NonNull
    public Instant component10() {
        return getPunishmentDate();
    }

    @Override
    @Nullable
    public String component11() {
        return getPunishmentMessage();
    }

    @Override
    @NonNull
    public Boolean component12() {
        return getPermanent();
    }

    @Override
    @NonNull
    public Boolean component13() {
        return getAutomatic();
    }

    @Override
    @Nullable
    public Instant component14() {
        return getPunishmentEndDate();
    }

    @Override
    @Nullable
    public String component15() {
        return getPunishmentEndReason();
    }

    @Override
    @NonNull
    public Boolean component16() {
        return getDidDm();
    }

    @Override
    @NonNull
    public Boolean component17() {
        return getEndDatePassed();
    }

    @Override
    @Nullable
    public Integer component18() {
        return getPunishmentEnder();
    }

    @Override
    @Nullable
    public String component19() {
        return getNamePunishmentEnder();
    }

    @Override
    @Nullable
    public String component20() {
        return getDiscrimPunishmentEnder();
    }

    @Override
    @NonNull
    public Boolean component21() {
        return getAutomaticEnd();
    }

    @Override
    @Nullable
    public Integer component22() {
        return getBatchId();
    }

    @Override
    @NonNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer value2() {
        return getUserIdPunished();
    }

    @Override
    @Nullable
    public String value3() {
        return getNamePunished();
    }

    @Override
    @Nullable
    public String value4() {
        return getDiscrimPunished();
    }

    @Override
    @NonNull
    public Integer value5() {
        return getUserIdPunisher();
    }

    @Override
    @Nullable
    public String value6() {
        return getNamePunisher();
    }

    @Override
    @Nullable
    public String value7() {
        return getDiscrimPunisher();
    }

    @Override
    @NonNull
    public Integer value8() {
        return getServerId();
    }

    @Override
    @NonNull
    public String value9() {
        return getPunishmentType();
    }

    @Override
    @NonNull
    public Instant value10() {
        return getPunishmentDate();
    }

    @Override
    @Nullable
    public String value11() {
        return getPunishmentMessage();
    }

    @Override
    @NonNull
    public Boolean value12() {
        return getPermanent();
    }

    @Override
    @NonNull
    public Boolean value13() {
        return getAutomatic();
    }

    @Override
    @Nullable
    public Instant value14() {
        return getPunishmentEndDate();
    }

    @Override
    @Nullable
    public String value15() {
        return getPunishmentEndReason();
    }

    @Override
    @NonNull
    public Boolean value16() {
        return getDidDm();
    }

    @Override
    @NonNull
    public Boolean value17() {
        return getEndDatePassed();
    }

    @Override
    @Nullable
    public Integer value18() {
        return getPunishmentEnder();
    }

    @Override
    @Nullable
    public String value19() {
        return getNamePunishmentEnder();
    }

    @Override
    @Nullable
    public String value20() {
        return getDiscrimPunishmentEnder();
    }

    @Override
    @NonNull
    public Boolean value21() {
        return getAutomaticEnd();
    }

    @Override
    @Nullable
    public Integer value22() {
        return getBatchId();
    }

    @Override
    @NonNull
    public PunishmentsRecord value1(@NonNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value2(@NonNull Integer value) {
        setUserIdPunished(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value3(@Nullable String value) {
        setNamePunished(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value4(@Nullable String value) {
        setDiscrimPunished(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value5(@NonNull Integer value) {
        setUserIdPunisher(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value6(@Nullable String value) {
        setNamePunisher(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value7(@Nullable String value) {
        setDiscrimPunisher(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value8(@NonNull Integer value) {
        setServerId(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value9(@NonNull String value) {
        setPunishmentType(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value10(@NonNull Instant value) {
        setPunishmentDate(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value11(@Nullable String value) {
        setPunishmentMessage(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value12(@NonNull Boolean value) {
        setPermanent(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value13(@NonNull Boolean value) {
        setAutomatic(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value14(@Nullable Instant value) {
        setPunishmentEndDate(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value15(@Nullable String value) {
        setPunishmentEndReason(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value16(@NonNull Boolean value) {
        setDidDm(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value17(@NonNull Boolean value) {
        setEndDatePassed(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value18(@Nullable Integer value) {
        setPunishmentEnder(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value19(@Nullable String value) {
        setNamePunishmentEnder(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value20(@Nullable String value) {
        setDiscrimPunishmentEnder(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value21(@NonNull Boolean value) {
        setAutomaticEnd(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord value22(@Nullable Integer value) {
        setBatchId(value);
        return this;
    }

    @Override
    @NonNull
    public PunishmentsRecord values(@NonNull Integer value1, @NonNull Integer value2, @Nullable String value3, @Nullable String value4, @NonNull Integer value5, @Nullable String value6, @Nullable String value7, @NonNull Integer value8, @NonNull String value9, @NonNull Instant value10, @Nullable String value11, @NonNull Boolean value12, @NonNull Boolean value13, @Nullable Instant value14, @Nullable String value15, @NonNull Boolean value16, @NonNull Boolean value17, @Nullable Integer value18, @Nullable String value19, @Nullable String value20, @NonNull Boolean value21, @Nullable Integer value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public PunishmentsRecord() {
        super(Punishments.PUNISHMENTS);
    }

    public PunishmentsRecord(@NonNull Integer id, @NonNull Integer userIdPunished, @Nullable String namePunished, @Nullable String discrimPunished, @NonNull Integer userIdPunisher, @Nullable String namePunisher, @Nullable String discrimPunisher, @NonNull Integer serverId, @NonNull String punishmentType, @NonNull Instant punishmentDate, @Nullable String punishmentMessage, @NonNull Boolean permanent, @NonNull Boolean automatic, @Nullable Instant punishmentEndDate, @Nullable String punishmentEndReason, @NonNull Boolean didDm, @NonNull Boolean endDatePassed, @Nullable Integer punishmentEnder, @Nullable String namePunishmentEnder, @Nullable String discrimPunishmentEnder, @NonNull Boolean automaticEnd, @Nullable Integer batchId) {
        super(Punishments.PUNISHMENTS);

        setId(id);
        setUserIdPunished(userIdPunished);
        setNamePunished(namePunished);
        setDiscrimPunished(discrimPunished);
        setUserIdPunisher(userIdPunisher);
        setNamePunisher(namePunisher);
        setDiscrimPunisher(discrimPunisher);
        setServerId(serverId);
        setPunishmentType(punishmentType);
        setPunishmentDate(punishmentDate);
        setPunishmentMessage(punishmentMessage);
        setPermanent(permanent);
        setAutomatic(automatic);
        setPunishmentEndDate(punishmentEndDate);
        setPunishmentEndReason(punishmentEndReason);
        setDidDm(didDm);
        setEndDatePassed(endDatePassed);
        setPunishmentEnder(punishmentEnder);
        setNamePunishmentEnder(namePunishmentEnder);
        setDiscrimPunishmentEnder(discrimPunishmentEnder);
        setAutomaticEnd(automaticEnd);
        setBatchId(batchId);
    }
}
