/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerMessages;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import discord4j.common.util.Snowflake;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.Instant;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerMessagesRecord extends UpdatableRecordImpl<ServerMessagesRecord> implements Record10<Integer, Snowflake, Integer, Snowflake, Integer, Snowflake, Instant, String, Boolean, String> {

    private static final long serialVersionUID = 1L;

    public ServerMessagesRecord setId(@NonNull Integer value) {
        set(0, value);
        return this;
    }

    @NonNull
    public Integer getId() {
        return (Integer) get(0);
    }

    public ServerMessagesRecord setMessageIdSnowflake(@NonNull Snowflake value) {
        set(1, value);
        return this;
    }

    @NonNull
    public Snowflake getMessageIdSnowflake() {
        return (Snowflake) get(1);
    }

    public ServerMessagesRecord setServerId(@NonNull Integer value) {
        set(2, value);
        return this;
    }

    @NonNull
    public Integer getServerId() {
        return (Integer) get(2);
    }

    public ServerMessagesRecord setServerIdSnowflake(@NonNull Snowflake value) {
        set(3, value);
        return this;
    }

    @NonNull
    public Snowflake getServerIdSnowflake() {
        return (Snowflake) get(3);
    }

    public ServerMessagesRecord setUserId(@NonNull Integer value) {
        set(4, value);
        return this;
    }

    @NonNull
    public Integer getUserId() {
        return (Integer) get(4);
    }

    public ServerMessagesRecord setUserIdSnowflake(@NonNull Snowflake value) {
        set(5, value);
        return this;
    }

    @NonNull
    public Snowflake getUserIdSnowflake() {
        return (Snowflake) get(5);
    }

    public ServerMessagesRecord setDate(@NonNull Instant value) {
        set(6, value);
        return this;
    }

    @NonNull
    public Instant getDate() {
        return (Instant) get(6);
    }

    public ServerMessagesRecord setContent(@Nullable String value) {
        set(7, value);
        return this;
    }

    @Nullable
    public String getContent() {
        return (String) get(7);
    }

    public ServerMessagesRecord setDeleted(@NonNull Boolean value) {
        set(8, value);
        return this;
    }

    @NonNull
    public Boolean getDeleted() {
        return (Boolean) get(8);
    }

    public ServerMessagesRecord setMessageData(@Nullable String value) {
        set(9, value);
        return this;
    }

    @Nullable
    public String getMessageData() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Row10<Integer, Snowflake, Integer, Snowflake, Integer, Snowflake, Instant, String, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    @NonNull
    public Row10<Integer, Snowflake, Integer, Snowflake, Integer, Snowflake, Instant, String, Boolean, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    @NonNull
    public Field<Integer> field1() {
        return ServerMessages.SERVER_MESSAGES.ID;
    }

    @Override
    @NonNull
    public Field<Snowflake> field2() {
        return ServerMessages.SERVER_MESSAGES.MESSAGE_ID_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Integer> field3() {
        return ServerMessages.SERVER_MESSAGES.SERVER_ID;
    }

    @Override
    @NonNull
    public Field<Snowflake> field4() {
        return ServerMessages.SERVER_MESSAGES.SERVER_ID_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Integer> field5() {
        return ServerMessages.SERVER_MESSAGES.USER_ID;
    }

    @Override
    @NonNull
    public Field<Snowflake> field6() {
        return ServerMessages.SERVER_MESSAGES.USER_ID_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Instant> field7() {
        return ServerMessages.SERVER_MESSAGES.DATE;
    }

    @Override
    @NonNull
    public Field<String> field8() {
        return ServerMessages.SERVER_MESSAGES.CONTENT;
    }

    @Override
    @NonNull
    public Field<Boolean> field9() {
        return ServerMessages.SERVER_MESSAGES.DELETED;
    }

    @Override
    @NonNull
    public Field<String> field10() {
        return ServerMessages.SERVER_MESSAGES.MESSAGE_DATA;
    }

    @Override
    @NonNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NonNull
    public Snowflake component2() {
        return getMessageIdSnowflake();
    }

    @Override
    @NonNull
    public Integer component3() {
        return getServerId();
    }

    @Override
    @NonNull
    public Snowflake component4() {
        return getServerIdSnowflake();
    }

    @Override
    @NonNull
    public Integer component5() {
        return getUserId();
    }

    @Override
    @NonNull
    public Snowflake component6() {
        return getUserIdSnowflake();
    }

    @Override
    @NonNull
    public Instant component7() {
        return getDate();
    }

    @Override
    @Nullable
    public String component8() {
        return getContent();
    }

    @Override
    @NonNull
    public Boolean component9() {
        return getDeleted();
    }

    @Override
    @Nullable
    public String component10() {
        return getMessageData();
    }

    @Override
    @NonNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NonNull
    public Snowflake value2() {
        return getMessageIdSnowflake();
    }

    @Override
    @NonNull
    public Integer value3() {
        return getServerId();
    }

    @Override
    @NonNull
    public Snowflake value4() {
        return getServerIdSnowflake();
    }

    @Override
    @NonNull
    public Integer value5() {
        return getUserId();
    }

    @Override
    @NonNull
    public Snowflake value6() {
        return getUserIdSnowflake();
    }

    @Override
    @NonNull
    public Instant value7() {
        return getDate();
    }

    @Override
    @Nullable
    public String value8() {
        return getContent();
    }

    @Override
    @NonNull
    public Boolean value9() {
        return getDeleted();
    }

    @Override
    @Nullable
    public String value10() {
        return getMessageData();
    }

    @Override
    @NonNull
    public ServerMessagesRecord value1(@NonNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value2(@NonNull Snowflake value) {
        setMessageIdSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value3(@NonNull Integer value) {
        setServerId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value4(@NonNull Snowflake value) {
        setServerIdSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value5(@NonNull Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value6(@NonNull Snowflake value) {
        setUserIdSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value7(@NonNull Instant value) {
        setDate(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value8(@Nullable String value) {
        setContent(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value9(@NonNull Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord value10(@Nullable String value) {
        setMessageData(value);
        return this;
    }

    @Override
    @NonNull
    public ServerMessagesRecord values(@NonNull Integer value1, @NonNull Snowflake value2, @NonNull Integer value3, @NonNull Snowflake value4, @NonNull Integer value5, @NonNull Snowflake value6, @NonNull Instant value7, @Nullable String value8, @NonNull Boolean value9, @Nullable String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ServerMessagesRecord() {
        super(ServerMessages.SERVER_MESSAGES);
    }

    public ServerMessagesRecord(@NonNull Integer id, @NonNull Snowflake messageIdSnowflake, @NonNull Integer serverId, @NonNull Snowflake serverIdSnowflake, @NonNull Integer userId, @NonNull Snowflake userIdSnowflake, @NonNull Instant date, @Nullable String content, @NonNull Boolean deleted, @Nullable String messageData) {
        super(ServerMessages.SERVER_MESSAGES);

        setId(id);
        setMessageIdSnowflake(messageIdSnowflake);
        setServerId(serverId);
        setServerIdSnowflake(serverIdSnowflake);
        setUserId(userId);
        setUserIdSnowflake(userIdSnowflake);
        setDate(date);
        setContent(content);
        setDeleted(deleted);
        setMessageData(messageData);
    }
}
