/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerProperties;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import discord4j.common.util.Snowflake;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerPropertiesRecord extends UpdatableRecordImpl<ServerPropertiesRecord> implements Record18<Integer, Integer, Snowflake, String, Long, Snowflake, Snowflake, Snowflake, Snowflake, Snowflake, Boolean, Snowflake, Integer, Integer, Integer, Integer, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    public ServerPropertiesRecord setId(@NonNull Integer value) {
        set(0, value);
        return this;
    }

    @NonNull
    public Integer getId() {
        return (Integer) get(0);
    }

    public ServerPropertiesRecord setServerId(@NonNull Integer value) {
        set(1, value);
        return this;
    }

    @NonNull
    public Integer getServerId() {
        return (Integer) get(1);
    }

    public ServerPropertiesRecord setServerIdSnowflake(@NonNull Snowflake value) {
        set(2, value);
        return this;
    }

    @NonNull
    public Snowflake getServerIdSnowflake() {
        return (Snowflake) get(2);
    }

    public ServerPropertiesRecord setServerName(@Nullable String value) {
        set(3, value);
        return this;
    }

    @Nullable
    public String getServerName() {
        return (String) get(3);
    }

    public ServerPropertiesRecord setMemberCountOnBotJoin(@NonNull Long value) {
        set(4, value);
        return this;
    }

    @NonNull
    public Long getMemberCountOnBotJoin() {
        return (Long) get(4);
    }

    public ServerPropertiesRecord setMutedRoleIdSnowflake(@Nullable Snowflake value) {
        set(5, value);
        return this;
    }

    @Nullable
    public Snowflake getMutedRoleIdSnowflake() {
        return (Snowflake) get(5);
    }

    public ServerPropertiesRecord setMemberLogChannelSnowflake(@Nullable Snowflake value) {
        set(6, value);
        return this;
    }

    @Nullable
    public Snowflake getMemberLogChannelSnowflake() {
        return (Snowflake) get(6);
    }

    public ServerPropertiesRecord setMessageLogChannelSnowflake(@Nullable Snowflake value) {
        set(7, value);
        return this;
    }

    @Nullable
    public Snowflake getMessageLogChannelSnowflake() {
        return (Snowflake) get(7);
    }

    public ServerPropertiesRecord setGuildLogChannelSnowflake(@Nullable Snowflake value) {
        set(8, value);
        return this;
    }

    @Nullable
    public Snowflake getGuildLogChannelSnowflake() {
        return (Snowflake) get(8);
    }

    public ServerPropertiesRecord setPunishmentLogChannelSnowflake(@Nullable Snowflake value) {
        set(9, value);
        return this;
    }

    @Nullable
    public Snowflake getPunishmentLogChannelSnowflake() {
        return (Snowflake) get(9);
    }

    public ServerPropertiesRecord setStopJoins(@NonNull Boolean value) {
        set(10, value);
        return this;
    }

    @NonNull
    public Boolean getStopJoins() {
        return (Boolean) get(10);
    }

    public ServerPropertiesRecord setModmailChannelSnowflake(@Nullable Snowflake value) {
        set(11, value);
        return this;
    }

    @Nullable
    public Snowflake getModmailChannelSnowflake() {
        return (Snowflake) get(11);
    }

    public ServerPropertiesRecord setMessagesToWarn(@NonNull Integer value) {
        set(12, value);
        return this;
    }

    @NonNull
    public Integer getMessagesToWarn() {
        return (Integer) get(12);
    }

    public ServerPropertiesRecord setWarnsToMute(@NonNull Integer value) {
        set(13, value);
        return this;
    }

    @NonNull
    public Integer getWarnsToMute() {
        return (Integer) get(13);
    }

    public ServerPropertiesRecord setPingsToWarn(@NonNull Integer value) {
        set(14, value);
        return this;
    }

    @NonNull
    public Integer getPingsToWarn() {
        return (Integer) get(14);
    }

    public ServerPropertiesRecord setJoinsToAntiraid(@NonNull Integer value) {
        set(15, value);
        return this;
    }

    @NonNull
    public Integer getJoinsToAntiraid() {
        return (Integer) get(15);
    }

    public ServerPropertiesRecord setAntiScam(@NonNull Boolean value) {
        set(16, value);
        return this;
    }

    @NonNull
    public Boolean getAntiScam() {
        return (Boolean) get(16);
    }

    public ServerPropertiesRecord setDehoist(@NonNull Boolean value) {
        set(17, value);
        return this;
    }

    @NonNull
    public Boolean getDehoist() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Row18<Integer, Integer, Snowflake, String, Long, Snowflake, Snowflake, Snowflake, Snowflake, Snowflake, Boolean, Snowflake, Integer, Integer, Integer, Integer, Boolean, Boolean> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    @NonNull
    public Row18<Integer, Integer, Snowflake, String, Long, Snowflake, Snowflake, Snowflake, Snowflake, Snowflake, Boolean, Snowflake, Integer, Integer, Integer, Integer, Boolean, Boolean> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    @NonNull
    public Field<Integer> field1() {
        return ServerProperties.SERVER_PROPERTIES.ID;
    }

    @Override
    @NonNull
    public Field<Integer> field2() {
        return ServerProperties.SERVER_PROPERTIES.SERVER_ID;
    }

    @Override
    @NonNull
    public Field<Snowflake> field3() {
        return ServerProperties.SERVER_PROPERTIES.SERVER_ID_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<String> field4() {
        return ServerProperties.SERVER_PROPERTIES.SERVER_NAME;
    }

    @Override
    @NonNull
    public Field<Long> field5() {
        return ServerProperties.SERVER_PROPERTIES.MEMBER_COUNT_ON_BOT_JOIN;
    }

    @Override
    @NonNull
    public Field<Snowflake> field6() {
        return ServerProperties.SERVER_PROPERTIES.MUTED_ROLE_ID_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Snowflake> field7() {
        return ServerProperties.SERVER_PROPERTIES.MEMBER_LOG_CHANNEL_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Snowflake> field8() {
        return ServerProperties.SERVER_PROPERTIES.MESSAGE_LOG_CHANNEL_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Snowflake> field9() {
        return ServerProperties.SERVER_PROPERTIES.GUILD_LOG_CHANNEL_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Snowflake> field10() {
        return ServerProperties.SERVER_PROPERTIES.PUNISHMENT_LOG_CHANNEL_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Boolean> field11() {
        return ServerProperties.SERVER_PROPERTIES.STOP_JOINS;
    }

    @Override
    @NonNull
    public Field<Snowflake> field12() {
        return ServerProperties.SERVER_PROPERTIES.MODMAIL_CHANNEL_SNOWFLAKE;
    }

    @Override
    @NonNull
    public Field<Integer> field13() {
        return ServerProperties.SERVER_PROPERTIES.MESSAGES_TO_WARN;
    }

    @Override
    @NonNull
    public Field<Integer> field14() {
        return ServerProperties.SERVER_PROPERTIES.WARNS_TO_MUTE;
    }

    @Override
    @NonNull
    public Field<Integer> field15() {
        return ServerProperties.SERVER_PROPERTIES.PINGS_TO_WARN;
    }

    @Override
    @NonNull
    public Field<Integer> field16() {
        return ServerProperties.SERVER_PROPERTIES.JOINS_TO_ANTIRAID;
    }

    @Override
    @NonNull
    public Field<Boolean> field17() {
        return ServerProperties.SERVER_PROPERTIES.ANTI_SCAM;
    }

    @Override
    @NonNull
    public Field<Boolean> field18() {
        return ServerProperties.SERVER_PROPERTIES.DEHOIST;
    }

    @Override
    @NonNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer component2() {
        return getServerId();
    }

    @Override
    @NonNull
    public Snowflake component3() {
        return getServerIdSnowflake();
    }

    @Override
    @Nullable
    public String component4() {
        return getServerName();
    }

    @Override
    @NonNull
    public Long component5() {
        return getMemberCountOnBotJoin();
    }

    @Override
    @Nullable
    public Snowflake component6() {
        return getMutedRoleIdSnowflake();
    }

    @Override
    @Nullable
    public Snowflake component7() {
        return getMemberLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake component8() {
        return getMessageLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake component9() {
        return getGuildLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake component10() {
        return getPunishmentLogChannelSnowflake();
    }

    @Override
    @NonNull
    public Boolean component11() {
        return getStopJoins();
    }

    @Override
    @Nullable
    public Snowflake component12() {
        return getModmailChannelSnowflake();
    }

    @Override
    @NonNull
    public Integer component13() {
        return getMessagesToWarn();
    }

    @Override
    @NonNull
    public Integer component14() {
        return getWarnsToMute();
    }

    @Override
    @NonNull
    public Integer component15() {
        return getPingsToWarn();
    }

    @Override
    @NonNull
    public Integer component16() {
        return getJoinsToAntiraid();
    }

    @Override
    @NonNull
    public Boolean component17() {
        return getAntiScam();
    }

    @Override
    @NonNull
    public Boolean component18() {
        return getDehoist();
    }

    @Override
    @NonNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer value2() {
        return getServerId();
    }

    @Override
    @NonNull
    public Snowflake value3() {
        return getServerIdSnowflake();
    }

    @Override
    @Nullable
    public String value4() {
        return getServerName();
    }

    @Override
    @NonNull
    public Long value5() {
        return getMemberCountOnBotJoin();
    }

    @Override
    @Nullable
    public Snowflake value6() {
        return getMutedRoleIdSnowflake();
    }

    @Override
    @Nullable
    public Snowflake value7() {
        return getMemberLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake value8() {
        return getMessageLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake value9() {
        return getGuildLogChannelSnowflake();
    }

    @Override
    @Nullable
    public Snowflake value10() {
        return getPunishmentLogChannelSnowflake();
    }

    @Override
    @NonNull
    public Boolean value11() {
        return getStopJoins();
    }

    @Override
    @Nullable
    public Snowflake value12() {
        return getModmailChannelSnowflake();
    }

    @Override
    @NonNull
    public Integer value13() {
        return getMessagesToWarn();
    }

    @Override
    @NonNull
    public Integer value14() {
        return getWarnsToMute();
    }

    @Override
    @NonNull
    public Integer value15() {
        return getPingsToWarn();
    }

    @Override
    @NonNull
    public Integer value16() {
        return getJoinsToAntiraid();
    }

    @Override
    @NonNull
    public Boolean value17() {
        return getAntiScam();
    }

    @Override
    @NonNull
    public Boolean value18() {
        return getDehoist();
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value1(@NonNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value2(@NonNull Integer value) {
        setServerId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value3(@NonNull Snowflake value) {
        setServerIdSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value4(@Nullable String value) {
        setServerName(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value5(@NonNull Long value) {
        setMemberCountOnBotJoin(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value6(@Nullable Snowflake value) {
        setMutedRoleIdSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value7(@Nullable Snowflake value) {
        setMemberLogChannelSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value8(@Nullable Snowflake value) {
        setMessageLogChannelSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value9(@Nullable Snowflake value) {
        setGuildLogChannelSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value10(@Nullable Snowflake value) {
        setPunishmentLogChannelSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value11(@NonNull Boolean value) {
        setStopJoins(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value12(@Nullable Snowflake value) {
        setModmailChannelSnowflake(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value13(@NonNull Integer value) {
        setMessagesToWarn(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value14(@NonNull Integer value) {
        setWarnsToMute(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value15(@NonNull Integer value) {
        setPingsToWarn(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value16(@NonNull Integer value) {
        setJoinsToAntiraid(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value17(@NonNull Boolean value) {
        setAntiScam(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord value18(@NonNull Boolean value) {
        setDehoist(value);
        return this;
    }

    @Override
    @NonNull
    public ServerPropertiesRecord values(@NonNull Integer value1, @NonNull Integer value2, @NonNull Snowflake value3, @Nullable String value4, @NonNull Long value5, @Nullable Snowflake value6, @Nullable Snowflake value7, @Nullable Snowflake value8, @Nullable Snowflake value9, @Nullable Snowflake value10, @NonNull Boolean value11, @Nullable Snowflake value12, @NonNull Integer value13, @NonNull Integer value14, @NonNull Integer value15, @NonNull Integer value16, @NonNull Boolean value17, @NonNull Boolean value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ServerPropertiesRecord() {
        super(ServerProperties.SERVER_PROPERTIES);
    }

    public ServerPropertiesRecord(@NonNull Integer id, @NonNull Integer serverId, @NonNull Snowflake serverIdSnowflake, @Nullable String serverName, @NonNull Long memberCountOnBotJoin, @Nullable Snowflake mutedRoleIdSnowflake, @Nullable Snowflake memberLogChannelSnowflake, @Nullable Snowflake messageLogChannelSnowflake, @Nullable Snowflake guildLogChannelSnowflake, @Nullable Snowflake punishmentLogChannelSnowflake, @NonNull Boolean stopJoins, @Nullable Snowflake modmailChannelSnowflake, @NonNull Integer messagesToWarn, @NonNull Integer warnsToMute, @NonNull Integer pingsToWarn, @NonNull Integer joinsToAntiraid, @NonNull Boolean antiScam, @NonNull Boolean dehoist) {
        super(ServerProperties.SERVER_PROPERTIES);

        setId(id);
        setServerId(serverId);
        setServerIdSnowflake(serverIdSnowflake);
        setServerName(serverName);
        setMemberCountOnBotJoin(memberCountOnBotJoin);
        setMutedRoleIdSnowflake(mutedRoleIdSnowflake);
        setMemberLogChannelSnowflake(memberLogChannelSnowflake);
        setMessageLogChannelSnowflake(messageLogChannelSnowflake);
        setGuildLogChannelSnowflake(guildLogChannelSnowflake);
        setPunishmentLogChannelSnowflake(punishmentLogChannelSnowflake);
        setStopJoins(stopJoins);
        setModmailChannelSnowflake(modmailChannelSnowflake);
        setMessagesToWarn(messagesToWarn);
        setWarnsToMute(warnsToMute);
        setPingsToWarn(pingsToWarn);
        setJoinsToAntiraid(joinsToAntiraid);
        setAntiScam(antiScam);
        setDehoist(dehoist);
    }
}
