/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerMessages;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerMessagesRecord extends UpdatableRecordImpl<ServerMessagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.server_messages.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.server_messages.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.server_messages.message_id_snowflake</code>.
     */
    public void setMessageIdSnowflake(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.server_messages.message_id_snowflake</code>.
     */
    public Long getMessageIdSnowflake() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>atropos.server_messages.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>atropos.server_messages.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>atropos.server_messages.server_id_snowflake</code>.
     */
    public void setServerIdSnowflake(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>atropos.server_messages.server_id_snowflake</code>.
     */
    public Long getServerIdSnowflake() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>atropos.server_messages.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>atropos.server_messages.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>atropos.server_messages.user_id_snowflake</code>.
     */
    public void setUserIdSnowflake(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>atropos.server_messages.user_id_snowflake</code>.
     */
    public Long getUserIdSnowflake() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>atropos.server_messages.date</code>.
     */
    public void setDate(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>atropos.server_messages.date</code>.
     */
    public Instant getDate() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>atropos.server_messages.content</code>.
     */
    public void setContent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>atropos.server_messages.content</code>.
     */
    public String getContent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>atropos.server_messages.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>atropos.server_messages.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>atropos.server_messages.message_data</code>.
     */
    public void setMessageData(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>atropos.server_messages.message_data</code>.
     */
    public String getMessageData() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerMessagesRecord
     */
    public ServerMessagesRecord() {
        super(ServerMessages.SERVER_MESSAGES);
    }

    /**
     * Create a detached, initialised ServerMessagesRecord
     */
    public ServerMessagesRecord(Integer id, Long messageIdSnowflake, Integer serverId, Long serverIdSnowflake, Integer userId, Long userIdSnowflake, Instant date, String content, Boolean deleted, String messageData) {
        super(ServerMessages.SERVER_MESSAGES);

        setId(id);
        setMessageIdSnowflake(messageIdSnowflake);
        setServerId(serverId);
        setServerIdSnowflake(serverIdSnowflake);
        setUserId(userId);
        setUserIdSnowflake(userIdSnowflake);
        setDate(date);
        setContent(content);
        setDeleted(deleted);
        setMessageData(messageData);
        resetChangedOnNotNull();
    }
}
