/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerCommandUses;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.Instant;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerCommandUsesRecord extends UpdatableRecordImpl<ServerCommandUsesRecord> implements Record6<Integer, Integer, Integer, String, Instant, Boolean> {

    private static final long serialVersionUID = 1L;

    public ServerCommandUsesRecord setId(@NonNull Integer value) {
        set(0, value);
        return this;
    }

    @NonNull
    public Integer getId() {
        return (Integer) get(0);
    }

    public ServerCommandUsesRecord setServerId(@NonNull Integer value) {
        set(1, value);
        return this;
    }

    @NonNull
    public Integer getServerId() {
        return (Integer) get(1);
    }

    public ServerCommandUsesRecord setCommandUserId(@NonNull Integer value) {
        set(2, value);
        return this;
    }

    @NonNull
    public Integer getCommandUserId() {
        return (Integer) get(2);
    }

    public ServerCommandUsesRecord setCommandContents(@NonNull String value) {
        set(3, value);
        return this;
    }

    @NonNull
    public String getCommandContents() {
        return (String) get(3);
    }

    public ServerCommandUsesRecord setDate(@Nullable Instant value) {
        set(4, value);
        return this;
    }

    @Nullable
    public Instant getDate() {
        return (Instant) get(4);
    }

    public ServerCommandUsesRecord setSuccess(@NonNull Boolean value) {
        set(5, value);
        return this;
    }

    @NonNull
    public Boolean getSuccess() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Row6<Integer, Integer, Integer, String, Instant, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    @NonNull
    public Row6<Integer, Integer, Integer, String, Instant, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    @NonNull
    public Field<Integer> field1() {
        return ServerCommandUses.SERVER_COMMAND_USES.ID;
    }

    @Override
    @NonNull
    public Field<Integer> field2() {
        return ServerCommandUses.SERVER_COMMAND_USES.SERVER_ID;
    }

    @Override
    @NonNull
    public Field<Integer> field3() {
        return ServerCommandUses.SERVER_COMMAND_USES.COMMAND_USER_ID;
    }

    @Override
    @NonNull
    public Field<String> field4() {
        return ServerCommandUses.SERVER_COMMAND_USES.COMMAND_CONTENTS;
    }

    @Override
    @NonNull
    public Field<Instant> field5() {
        return ServerCommandUses.SERVER_COMMAND_USES.DATE;
    }

    @Override
    @NonNull
    public Field<Boolean> field6() {
        return ServerCommandUses.SERVER_COMMAND_USES.SUCCESS;
    }

    @Override
    @NonNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer component2() {
        return getServerId();
    }

    @Override
    @NonNull
    public Integer component3() {
        return getCommandUserId();
    }

    @Override
    @NonNull
    public String component4() {
        return getCommandContents();
    }

    @Override
    @Nullable
    public Instant component5() {
        return getDate();
    }

    @Override
    @NonNull
    public Boolean component6() {
        return getSuccess();
    }

    @Override
    @NonNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NonNull
    public Integer value2() {
        return getServerId();
    }

    @Override
    @NonNull
    public Integer value3() {
        return getCommandUserId();
    }

    @Override
    @NonNull
    public String value4() {
        return getCommandContents();
    }

    @Override
    @Nullable
    public Instant value5() {
        return getDate();
    }

    @Override
    @NonNull
    public Boolean value6() {
        return getSuccess();
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value1(@NonNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value2(@NonNull Integer value) {
        setServerId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value3(@NonNull Integer value) {
        setCommandUserId(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value4(@NonNull String value) {
        setCommandContents(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value5(@Nullable Instant value) {
        setDate(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord value6(@NonNull Boolean value) {
        setSuccess(value);
        return this;
    }

    @Override
    @NonNull
    public ServerCommandUsesRecord values(@NonNull Integer value1, @NonNull Integer value2, @NonNull Integer value3, @NonNull String value4, @Nullable Instant value5, @NonNull Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ServerCommandUsesRecord() {
        super(ServerCommandUses.SERVER_COMMAND_USES);
    }

    public ServerCommandUsesRecord(@NonNull Integer id, @NonNull Integer serverId, @NonNull Integer commandUserId, @NonNull String commandContents, @Nullable Instant date, @NonNull Boolean success) {
        super(ServerCommandUses.SERVER_COMMAND_USES);

        setId(id);
        setServerId(serverId);
        setCommandUserId(commandUserId);
        setCommandContents(commandContents);
        setDate(date);
        setSuccess(success);
    }
}
