/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerBlacklist;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerBlacklistRecord extends UpdatableRecordImpl<ServerBlacklistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.server_blacklist.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.server_blacklist.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.server_blacklist.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.server_blacklist.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atropos.server_blacklist.regex_trigger</code>.
     */
    public void setRegexTrigger(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>atropos.server_blacklist.regex_trigger</code>.
     */
    public String getRegexTrigger() {
        return (String) get(2);
    }

    /**
     * Setter for <code>atropos.server_blacklist.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>atropos.server_blacklist.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>atropos.server_blacklist.action</code>.
     */
    public void setAction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>atropos.server_blacklist.action</code>.
     */
    public String getAction() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerBlacklistRecord
     */
    public ServerBlacklistRecord() {
        super(ServerBlacklist.SERVER_BLACKLIST);
    }

    /**
     * Create a detached, initialised ServerBlacklistRecord
     */
    public ServerBlacklistRecord(Integer id, Integer serverId, String regexTrigger, String type, String action) {
        super(ServerBlacklist.SERVER_BLACKLIST);

        setId(id);
        setServerId(serverId);
        setRegexTrigger(regexTrigger);
        setType(type);
        setAction(action);
        resetChangedOnNotNull();
    }
}
