/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerProperties;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerPropertiesRecord extends UpdatableRecordImpl<ServerPropertiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.server_properties.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.server_properties.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.server_properties.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.server_properties.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atropos.server_properties.server_id_snowflake</code>.
     */
    public void setServerIdSnowflake(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>atropos.server_properties.server_id_snowflake</code>.
     */
    public Long getServerIdSnowflake() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>atropos.server_properties.server_name</code>.
     */
    public void setServerName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>atropos.server_properties.server_name</code>.
     */
    public String getServerName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.member_count_on_bot_join</code>.
     */
    public void setMemberCountOnBotJoin(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.member_count_on_bot_join</code>.
     */
    public Long getMemberCountOnBotJoin() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.muted_role_id_snowflake</code>.
     */
    public void setMutedRoleIdSnowflake(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.muted_role_id_snowflake</code>.
     */
    public Long getMutedRoleIdSnowflake() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.member_log_channel_snowflake</code>.
     */
    public void setMemberLogChannelSnowflake(Long value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.member_log_channel_snowflake</code>.
     */
    public Long getMemberLogChannelSnowflake() {
        return (Long) get(6);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.message_log_channel_snowflake</code>.
     */
    public void setMessageLogChannelSnowflake(Long value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.message_log_channel_snowflake</code>.
     */
    public Long getMessageLogChannelSnowflake() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.guild_log_channel_snowflake</code>.
     */
    public void setGuildLogChannelSnowflake(Long value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.guild_log_channel_snowflake</code>.
     */
    public Long getGuildLogChannelSnowflake() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.punishment_log_channel_snowflake</code>.
     */
    public void setPunishmentLogChannelSnowflake(Long value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.punishment_log_channel_snowflake</code>.
     */
    public Long getPunishmentLogChannelSnowflake() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>atropos.server_properties.stop_joins</code>.
     */
    public void setStopJoins(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>atropos.server_properties.stop_joins</code>.
     */
    public Boolean getStopJoins() {
        return (Boolean) get(10);
    }

    /**
     * Setter for
     * <code>atropos.server_properties.modmail_channel_snowflake</code>.
     */
    public void setModmailChannelSnowflake(Long value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>atropos.server_properties.modmail_channel_snowflake</code>.
     */
    public Long getModmailChannelSnowflake() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>atropos.server_properties.messages_to_warn</code>.
     */
    public void setMessagesToWarn(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>atropos.server_properties.messages_to_warn</code>.
     */
    public Integer getMessagesToWarn() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>atropos.server_properties.warns_to_mute</code>.
     */
    public void setWarnsToMute(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>atropos.server_properties.warns_to_mute</code>.
     */
    public Integer getWarnsToMute() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>atropos.server_properties.pings_to_warn</code>.
     */
    public void setPingsToWarn(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>atropos.server_properties.pings_to_warn</code>.
     */
    public Integer getPingsToWarn() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>atropos.server_properties.joins_to_antiraid</code>.
     */
    public void setJoinsToAntiraid(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>atropos.server_properties.joins_to_antiraid</code>.
     */
    public Integer getJoinsToAntiraid() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>atropos.server_properties.anti_scam</code>.
     */
    public void setAntiScam(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>atropos.server_properties.anti_scam</code>.
     */
    public Boolean getAntiScam() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>atropos.server_properties.dehoist</code>.
     */
    public void setDehoist(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>atropos.server_properties.dehoist</code>.
     */
    public Boolean getDehoist() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerPropertiesRecord
     */
    public ServerPropertiesRecord() {
        super(ServerProperties.SERVER_PROPERTIES);
    }

    /**
     * Create a detached, initialised ServerPropertiesRecord
     */
    public ServerPropertiesRecord(Integer id, Integer serverId, Long serverIdSnowflake, String serverName, Long memberCountOnBotJoin, Long mutedRoleIdSnowflake, Long memberLogChannelSnowflake, Long messageLogChannelSnowflake, Long guildLogChannelSnowflake, Long punishmentLogChannelSnowflake, Boolean stopJoins, Long modmailChannelSnowflake, Integer messagesToWarn, Integer warnsToMute, Integer pingsToWarn, Integer joinsToAntiraid, Boolean antiScam, Boolean dehoist) {
        super(ServerProperties.SERVER_PROPERTIES);

        setId(id);
        setServerId(serverId);
        setServerIdSnowflake(serverIdSnowflake);
        setServerName(serverName);
        setMemberCountOnBotJoin(memberCountOnBotJoin);
        setMutedRoleIdSnowflake(mutedRoleIdSnowflake);
        setMemberLogChannelSnowflake(memberLogChannelSnowflake);
        setMessageLogChannelSnowflake(messageLogChannelSnowflake);
        setGuildLogChannelSnowflake(guildLogChannelSnowflake);
        setPunishmentLogChannelSnowflake(punishmentLogChannelSnowflake);
        setStopJoins(stopJoins);
        setModmailChannelSnowflake(modmailChannelSnowflake);
        setMessagesToWarn(messagesToWarn);
        setWarnsToMute(warnsToMute);
        setPingsToWarn(pingsToWarn);
        setJoinsToAntiraid(joinsToAntiraid);
        setAntiScam(antiScam);
        setDehoist(dehoist);
        resetChangedOnNotNull();
    }
}
