/*
 * This file is generated by jOOQ.
 */
package dev.laarryy.atropos.jooq.tables.records;


import dev.laarryy.atropos.jooq.tables.ServerRolePermissions;
import discord4j.common.util.Snowflake;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServerRolePermissionsRecord extends UpdatableRecordImpl<ServerRolePermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atropos.server_role_permissions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>atropos.server_role_permissions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>atropos.server_role_permissions.server_id</code>.
     */
    public void setServerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>atropos.server_role_permissions.server_id</code>.
     */
    public Integer getServerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atropos.server_role_permissions.permission_id</code>.
     */
    public void setPermissionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>atropos.server_role_permissions.permission_id</code>.
     */
    public Integer getPermissionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>atropos.server_role_permissions.role_id_snowflake</code>.
     */
    public void setRoleIdSnowflake(Snowflake value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>atropos.server_role_permissions.role_id_snowflake</code>.
     */
    public Snowflake getRoleIdSnowflake() {
        return (Snowflake) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerRolePermissionsRecord
     */
    public ServerRolePermissionsRecord() {
        super(ServerRolePermissions.SERVER_ROLE_PERMISSIONS);
    }

    /**
     * Create a detached, initialised ServerRolePermissionsRecord
     */
    public ServerRolePermissionsRecord(Integer id, Integer serverId, Integer permissionId, Snowflake roleIdSnowflake) {
        super(ServerRolePermissions.SERVER_ROLE_PERMISSIONS);

        setId(id);
        setServerId(serverId);
        setPermissionId(permissionId);
        setRoleIdSnowflake(roleIdSnowflake);
        resetChangedOnNotNull();
    }
}
